### PR TITLE
Add polyfill for css transform property for old browsers

### PR DESCRIPTION
**Pull request by engmagdy87**
Add polyfill for css transform property for old browsers and native browsers on mobile

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Hi, thanks for the PR but I cannot merge it as it is. You've modified every line in TagCloud.js which makes it unable to see the relevant changes. Please commit only the relevant changes without any styling modifications. If you want to change the styling (" i.s.o ') then do so in a separate PR.
Cheers

**Comment by engmagdy87** [comment]
hi @IjzerenHein 
prettier extension reformat the file so it appear that i changed all the file
i created a branch and commits only relevant changes
should i create new PR ?

**Comment by engmagdy87** [comment]
hi @IjzerenHein 
prettier extension reformat the file so it appear that i changed all the file
i created a branch and commits only relevant changes
should i create new PR ?

**Comment by IjzerenHein** [comment]
Hi Mohamed, yes creating a new PR without the prettier reformat is probably the best solution.
regards.

**Pull request closed without merging**
